Classes vs struct
Manithj/learning_Cpp pull request #3
Opened 2023-03-16 05:52 UTC by Manithj

2023-03-16 09:13 UTC, PramudithaPothuwila requested changes
Remove Indentation mentioned in the comment

2023-03-16 09:13 UTC, PramudithaPothuwila commented on Documentation/3. Classes vs Struct/README.md
> +      public:
Remove Indentation of public:

2023-03-16 09:13 UTC, PramudithaPothuwila commented on Documentation/3. Classes vs Struct/README.md
> +     public:
Remove Indentation

2023-03-17 02:52 UTC, Manithj commented on Documentation/3. Classes vs Struct/README.md
> +      public:
Done

2023-03-17 02:52 UTC, Manithj commented on Documentation/3. Classes vs Struct/README.md
> +     public:
Done

2023-03-17 13:18 UTC, PramudithaPothuwila requested changes

2023-03-17 13:18 UTC, PramudithaPothuwila commented on Documentation/3. Classes vs Struct/README.md
> +{
```C++
class Student    
{    
public:  
   int id;  //field or data member     
   float salary; //field or data member  
   String name;//field or data member    
}
```

2023-03-17 13:28 UTC, Manithj commented on Documentation/3. Classes vs Struct/README.md
> +{
fixed

2023-03-17 13:40 UTC, PramudithaPothuwila approved these changes

2023-03-17 13:40 UTC, merged